development:
  adapter: postgresql
  database: acrar_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: acrar_test
  username: postgres
  pool: 5
  timeout: 5000

# This will be overwritten during deployment to Heroku and is here for Rake tasks.
production:
  adapter: postgresql
  database: acrar_production
  pool: 5
  timeout: 5000
