# By default, this is set up to use the sqlite3 adapter in order to
# speed up local dev setup. It is recommended that you switch to
# postgresql to ensure consistency between dev, test and production
development:
  adapter: postgresql
  database: development

test:
  adapter: postgresql
  database: test

# This will be overwritten during deployment to Heroku and is here for Rake tasks.
production:
  adapter: postgresql
  database: production
